version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: ${HOME}/.reup/logs/reup.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  security:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: ${HOME}/.reup/logs/security.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

loggers:
  reup:
    level: INFO
    handlers: [console, file]
    propagate: no

  reup.security:
    level: INFO
    handlers: [security]
    propagate: no

root:
  level: INFO
  handlers: [console] 